### ISSUE TITLE
Less results with less restrictive query

### ISSUE THREAD

**Issue by camilstaps** [annotation/text-methods#1]
The following search on the BHSA app gives 617 results:

```
clause
  phrase typ=PP function=Adju
  phrase typ=VP function=Pred
    word vs=nif|hit|htpo
```

When I add a `prep` node I get 696 results:

```
clause
  phrase typ=PP function=Adju
    word sp=prep
  phrase typ=VP function=Pred
    word vs=nif|hit|htpo
```

I would expect the second query to give less or equally many results as the first, or do I overlook something?

**Comment by codykingham** [comment]
@camilstaps It was a great question! Now we've archived it here in `text-methods` and in the future people can refer back to it. @oliverglanz @dirkroorda here is a nice example of the kinds of questions we should start to archive here!

**Comment by codykingham** [comment]
I've added the `bhsa` tag to this particular question

**Comment by dirkroorda** [comment]
It's a very good question. You do find less resulting clause, phrase, phrase triplets, but the query expanded the concept of result to quartets, and there turn out to be more quartets than triplets.
By the way, look also at https://annotation.github.io/text-fabric/Api/Search/, and note the `shallow` parameter. This comes very close to the point in question.

**Comment by dirkroorda** [comment]
And there is a device to get exactly what you intended here, @camilstaps 
```
clause
  phrase typ=PP function=Adju
  /with/
    word sp=prep
  /-/
  phrase typ=VP function=Pred
    word vs=nif|hit|htpo
```
which gives 598 results.
Quantified pieces of the template do not contribute to the result tuples.

**Comment by camilstaps** [comment]
Thanks, @dirkroorda. I was actually looking to get the preposition as well, so I'm using the query with 696 results now, but you couldn't know that.

Finally, for those wondering why that last query gives 598 results and not 617 (a PP always contains a P, right?), I should have used the `pdp` feature (phrase-dependent part of speech) instead of `sp` (part of speech).

**Comment by codykingham** [comment]
Also, if you have stacked prepositions, you might also specify that you only want the leading preposition. You can do that by looking for a preposition not preceded by another preposition:

```
clause
  phrase typ=PP function=Adju
    w:word pdp=prep
    /without/
   word pdp=prep
   <: w
   /-/
  phrase typ=VP function=Pred
    word vs=nif|hit|htpo
```
